### ISSUE TITLE
Link clickable in the blank space

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [tejaspundlik/personal-website#1]
In space between two icons link is clickable

**Comment by abitsalihu** [comment]
Hey @Aatmaj-Zephyr, I would like to help with this issue. :)

**Comment by tejaspundlik** [comment]
@abitsalihu please do :)

**Comment by abitsalihu** [comment]
@tejaspundlik you told me to work on this issue and then closed the issue.. I'm guessing the issue has been resolved?

**Comment by tejaspundlik** [comment]
Yes it has been resolved

**Comment by Aatmaj-Zephyr** [comment]
@abitsalihu , some issue still is present. The link is still clickable around edges as noticed by @tejaspundlik maybe you would like to work on that..

**Comment by tejaspundlik** [comment]
<img width="795" alt="Screenshot 2022-09-28 at 10 55 13 PM" src="https://user-images.githubusercontent.com/101443790/193020171-fb7c0cad-0e3e-4d1c-8151-19272f0698b4.png">
@abitsalihu If you can see the small box at the bottom right and left edges of the social media icon, it seems they are clickable

**Comment by Aatmaj-Zephyr** [comment]
Is this solved?

**Comment by tejaspundlik** [comment]
No

**Comment by Aatmaj-Zephyr** [comment]
Then open it
